apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: fastapi-async-sqlmodel
  annotations:
    github.com/project-slug: Cedric-Magnan/fastapi-async-sqlmodel
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
spec:
  type: service
  lifecycle: production
  owner: Cedric-Magnan
